import { Redirect, useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { markConversationRead, sendTextMessage, setTypingState, subscribeToUser } from '@/services/chat';
import { useMessages, useTypingState } from '@/hooks/useChat';
export default function ChatScreen() { const { user } = useAuth(); const router = useRouter(); const p = useLocalSearchParams<{ conversationId: string; otherUid?: string; otherName?: string }>(); const id = String(p.conversationId || ''); const otherUid = String(p.otherUid || ''); const fallbackName = String(p.otherName || 'Chat'); const { items, loading, loadingOlder, hasMore, loadOlder } = useMessages(id); const typing = useTypingState(id); const [text, setText] = useState(''); const [sending, setSending] = useState(false); const [profile, setProfile] = useState<any>(null);
useEffect(() => { if (!user || !id) return; markConversationRead(id, user.uid).catch(() => undefined); if (!otherUid) return; return subscribeToUser(otherUid, setProfile); }, [user?.uid, id, otherUid]);
useEffect(() => { if (!user || !id) return; if (!text.trim()) { setTypingState(id, user.uid, false).catch(() => undefined); return; } setTypingState(id, user.uid, true).catch(() => undefined); const timer = setTimeout(() => setTypingState(id, user.uid, false).catch(() => undefined), 1000); return () => { clearTimeout(timer); setTypingState(id, user.uid, false).catch(() => undefined); }; }, [text, user?.uid, id]);
if (!user) return <Redirect href="/auth/login" />; async function send() { if (!text.trim() || !otherUid || sending) return; const value = text; setText(''); setSending(true); try { await sendTextMessage(id, user.uid, otherUid, value); } catch { setText(value); } finally { setSending(false); } }
return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>‹</Text></Pressable><View style={s.center}><Text style={s.title}>{profile?.displayName || fallbackName}</Text><Text style={profile?.isOnline ? s.online : s.offline}>{profile?.isOnline ? 'online' : 'offline'}</Text></View><View style={s.spacer} /></View>{loading ? <ActivityIndicator color="#38bdf8" style={s.loader} /> : <><Pressable style={s.older} onPress={() => loadOlder()} disabled={loadingOlder || !hasMore}><Text style={s.olderText}>{loadingOlder ? 'Loading…' : hasMore ? 'Load older messages' : 'No older messages'}</Text></Pressable><FlatList data={items} keyExtractor={m => m.id} contentContainerStyle={s.messages} ListEmptyComponent={<Text style={s.empty}>No messages yet. Say hello!</Text>} renderItem={({ item }) => <View style={[s.bubble, item.senderId === user.uid ? s.mine : s.theirs]}><Text style={s.message}>{item.isDeleted ? 'Message deleted' : item.text}</Text><Text style={s.timestamp}>{item.createdAt ? item.createdAt.toDate().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'sending…'}{item.senderId === user.uid && item.readBy?.includes(otherUid) ? '  · Read' : ''}</Text></View>} /></>} />}{typing.some(uid => uid !== user.uid) && <Text style={s.typing}>{profile?.displayName || fallbackName} is typing…</Text>}<View style={s.composer}><TextInput style={s.input} placeholder="Message" placeholderTextColor="#64748b" value={text} onChangeText={setText} multiline maxLength={4000} /><Pressable style={s.send} onPress={send} disabled={sending}><Text style={s.sendText}>{sending ? '…' : 'Send'}</Text></Pressable></View></KeyboardAvoidingView>; }
const s = StyleSheet.create({ screen:{flex:1,backgroundColor:'#020817'},header:{paddingTop:54,paddingHorizontal:18,paddingBottom:16,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#0f172a'},back:{color:'#38bdf8',fontSize:38,lineHeight:34,width:40},center:{flex:1,alignItems:'center'},title:{color:'#f8fafc',fontSize:20,fontWeight:'800'},online:{color:'#4ade80',fontSize:12},offline:{color:'#94a3b8',fontSize:12},spacer:{width:40},loader:{marginTop:60},older:{paddingVertical:8,alignItems:'center'},olderText:{color:'#38bdf8',fontSize:13,fontWeight:'700'},messages:{padding:16,gap:10,flexGrow:1,justifyContent:'flex-end'},empty:{color:'#64748b',textAlign:'center',marginBottom:30},bubble:{maxWidth:'82%',padding:11,borderRadius:16},mine:{alignSelf:'flex-end',backgroundColor:'#0369a1',borderBottomRightRadius:4},theirs:{alignSelf:'flex-start',backgroundColor:'#1e293b',borderBottomLeftRadius:4},message:{color:'#f8fafc',fontSize:16,lineHeight:21},timestamp:{color:'#bae6fd',fontSize:10,marginTop:4,alignSelf:'flex-end'},typing:{color:'#94a3b8',paddingHorizontal:16,paddingBottom:8},composer:{flexDirection:'row',alignItems:'flex-end',gap:8,padding:12,borderTopWidth:1,borderTopColor:'#0f172a'},input:{flex:1,maxHeight:110,backgroundColor:'#0f172a',borderRadius:18,paddingHorizontal:15,paddingVertical:11,color:'#f8fafc'},send:{backgroundColor:'#38bdf8',borderRadius:18,paddingHorizontal:16,paddingVertical:12},sendText:{color:'#020817',fontWeight:'800'}});
