import { Redirect, useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, KeyboardAvoidingView, Linking, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { markConversationRead, sendMediaMessage, sendTextMessage, setTypingState, subscribeToUser } from '@/services/chat';
import { enqueueTextMessage } from '@/services/offlineQueue';
import { pickDocument, pickImage, pickVideo, type PickedMedia } from '@/services/media';
import { uploadMedia } from '@/services/mediaStorage';
import { useMessages, useTypingState } from '@/hooks/useChat';
export default function ChatScreen() { const { user } = useAuth(); const router = useRouter(); const p = useLocalSearchParams<{ conversationId: string; otherUid?: string; otherName?: string }>(); const id = String(p.conversationId || ''); const otherUid = String(p.otherUid || ''); const fallbackName = String(p.otherName || 'Chat'); const { items, loading } = useMessages(id); const typing = useTypingState(id); const [text, setText] = useState(''); const [sending, setSending] = useState(false); const [profile, setProfile] = useState<any>(null);
useEffect(() => { if (!user || !id) return; markConversationRead(id, user.uid).catch(() => undefined); if (!otherUid) return; return subscribeToUser(otherUid, setProfile); }, [user?.uid, id, otherUid]);
useEffect(() => { if (!user || !id) return; if (!text.trim()) { setTypingState(id, user.uid, false).catch(() => undefined); return; } setTypingState(id, user.uid, true).catch(() => undefined); const timer = setTimeout(() => setTypingState(id, user.uid, false).catch(() => undefined), 1000); return () => { clearTimeout(timer); setTypingState(id, user.uid, false).catch(() => undefined); }; }, [text, user?.uid, id]);
if (!user) return <Redirect href="/auth/login" />;
async function send() { if (!text.trim() || !otherUid || sending) return; const value = text.trim(); setText(''); setSending(true); try { await sendTextMessage(id, user.uid, otherUid, value); } catch { await enqueueTextMessage({ id: `${user.uid}-${Date.now()}`, conversationId: id, senderId: user.uid, receiverId: otherUid, text: value, createdAt: Date.now() }); Alert.alert('Saved offline', 'Your message will send when you reconnect.'); } finally { setSending(false); } }
async function sendMedia(pick: () => Promise<PickedMedia | null>, kind: 'image' | 'video' | 'document') { if (!otherUid || sending) return; try { setSending(true); const file = await pick(); if (!file) return; const uploaded = await uploadMedia(file); await sendMediaMessage(id, user.uid, otherUid, kind, uploaded); } catch (error) { Alert.alert('Media failed', error instanceof Error ? error.message : 'Could not send this file.'); } finally { setSending(false); } }
return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>‹</Text></Pressable><View style={s.center}><Text style={s.title}>{profile?.displayName || fallbackName}</Text><Text style={profile?.isOnline ? s.online : s.offline}>{profile?.isOnline ? 'online' : 'offline'}</Text></View><View style={s.spacer} /></View>{loading ? <ActivityIndicator color="#38bdf8" style={s.loader} /> : <FlatList data={items} keyExtractor={m => m.id} contentContainerStyle={s.messages} ListEmptyComponent={<Text style={s.empty}>No messages yet. Say hello!</Text>} renderItem={({ item }) => <View style={[s.bubble, item.senderId === user.uid ? s.mine : s.theirs]}>{item.type === 'image' && item.attachment ? <Pressable onPress={() => Linking.openURL(item.attachment!.url)}><Image source={{ uri: item.attachment.url }} style={s.image} /></Pressable> : <Pressable disabled={!item.attachment?.url} onPress={() => item.attachment?.url && Linking.openURL(item.attachment.url)}><Text style={s.message}>{item.isDeleted ? 'Message deleted' : item.type === 'text' ? item.text : `📎 ${item.attachment?.name || 'Attachment'}`}</Text></Pressable>}<Text style={s.timestamp}>{item.createdAt ? item.createdAt.toDate().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'sending…'}{item.senderId === user.uid && item.readBy?.includes(otherUid) ? ' · Read' : ''}</Text></View>} />} /><View style={s.actions}><Pressable onPress={() => sendMedia(pickImage, 'image')}><Text style={s.action}>Photo</Text></Pressable><Pressable onPress={() => sendMedia(pickVideo, 'video')}><Text style={s.action}>Video</Text></Pressable><Pressable onPress={() => sendMedia(pickDocument, 'document')}><Text style={s.action}>File</Text></Pressable></View><View style={s.composer}><TextInput style={s.input} placeholder="Message" placeholderTextColor="#64748b" value={text} onChangeText={setText} multiline maxLength={4000} /><Pressable style={s.send} onPress={send} disabled={sending}><Text style={s.sendText}>{sending ? '…' : 'Send'}</Text></Pressable></View></KeyboardAvoidingView>; }
const s = StyleSheet.create({ screen:{flex:1,backgroundColor:'#020817'},header:{paddingTop:54,paddingHorizontal:18,paddingBottom:16,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#0f172a'},back:{color:'#38bdf8',fontSize:38,lineHeight:34,width:40},center:{flex:1,alignItems:'center'},title:{color:'#f8fafc',fontSize:20,fontWeight:'800'},online:{color:'#4ade80',fontSize:12},offline:{color:'#94a3b8',fontSize:12},spacer:{width:40},loader:{marginTop:60},messages:{padding:16,gap:10,flexGrow:1,justifyContent:'flex-end'},empty:{color:'#64748b',textAlign:'center',marginBottom:30},bubble:{maxWidth:'82%',padding:11,borderRadius:16},mine:{alignSelf:'flex-end',backgroundColor:'#0369a1',borderBottomRightRadius:4},theirs:{alignSelf:'flex-start',backgroundColor:'#1e293b',borderBottomLeftRadius:4},message:{color:'#f8fafc',fontSize:16,lineHeight:21},image:{width:220,height:180,borderRadius:10},timestamp:{color:'#bae6fd',fontSize:10,marginTop:4,alignSelf:'flex-end'},actions:{flexDirection:'row',gap:18,paddingHorizontal:16,paddingVertical:7},action:{color:'#38bdf8',fontWeight:'700'},composer:{flexDirection:'row',alignItems:'flex-end',gap:8,padding:12,borderTopWidth:1,borderTopColor:'#0f172a'},input:{flex:1,maxHeight:110,backgroundColor:'#0f172a',borderRadius:18,paddingHorizontal:15,paddingVertical:11,color:'#f8fafc'},send:{backgroundColor:'#38bdf8',borderRadius:18,paddingHorizontal:16,paddingVertical:12},sendText:{color:'#020817',fontWeight:'800'}});
